<a href="https://colab.research.google.com/github/mann09/cds_mini_projects/blob/main/M1_NB_MiniProject_1_Linear_Algebra_and_Calculus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mini Project on Solving Linear Systems of Linear Equations using Matrices, and Rate Equations using Direct Differentiation using Python

## Problem Statement

 The task is to advise a petroleum company on how to meet the demands of their customers for motor oil, diesel oil and gasoline.

## Learning Objectives

At the end of the experiment, you will be able to

* create arrays and matrices in python
* understand the concepts of linear equations
* solve the system of linear equations

### Data

From a barrel of crude oil, in one day, factory $A$ can produce
* 20 gallons of motor oil,
* 10 gallons of diesel oil, and
* 5 gallons of gasoline

Similarly, factory $B$ can produce
* 4 gallons of motor oil,
* 14 gallons of diesel oil, and
* 5 gallons of gasoline

while factory $C$ can produce
* 4 gallons of motor oil,
* 5 gallons of diesel oil, and
* 12 gallons of gasoline

There is also waste in the form of paraffin, among other things. Factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude, factory $B$ 5 gallons, and factory $C$ 2 gallons.

**Note:** Your conclusion should include a discussion of the nature of the terms *unique*, *no solution*, *overdetermined* and *underdetermined* as they apply in the context of the oil plants.

## Grading = 10 Points

### Create an array

Create an array of size 2x3 with arbitrary values.

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
import scipy.misc
import sympy as sy
from scipy.linalg import solve
import random as rnd

In [ ]:
Rows = int(input("Give the number of rows:"))
Columns = int(input("Give the number of columns:"))

# Initializing the matrix
a_matrix = []

# taking Rows and Columns matrix from the user
for i in range(Rows):
    # taking input for the row elements from the user  input in a single go separated by space e.g. 1 2 3
    single_row = list(map(int, input().split()))
    # appending the 'single_row' to the 'a_matrix'
    a_matrix.append(single_row)
# printing a_matrix given by user

any_array_of_any_size=np.array(a_matrix)

Give the number of rows:2
Give the number of columns:3
1 2 3
4 5 6


In [ ]:
any_array_of_any_size

array([[1, 2, 3],
       [4, 5, 6]])

### Create the system of Linear Equations

Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation. Please include the units as well.

Let the number of barrels used by factory $A$, $B$ and $C$ are $x$, $y$ and $z$ respectively.

Then the system of linear equations will be

$$Motor\ oil:\ \ \ 20x + 4y + 4z = 6600$$

$$Diesel\ oil:\ \ \ 10x + 14y + 5z = 5100$$

$$Gasoline:\ \ \ 5x + 5y + 12z = 3100$$

### Solve the system of Linear Equation (2 points)

How many barrels of crude oil each plant should get in order to meet the demand as a group. Remember that we can only provide each plant with an integral number of barrels.

**Production capacity multiplied by barrels of crude oil gives us demand of distributors in Gallons**

**Production capacity** in **Gallons** will be represented by **cap** and will be stored in an Numpy array

**Crude oil volume** in **Barrels** will be represented by **cov**

**Demand of distributors** in **Gallons** will be represented by **dod**



---



###**(PRODUCTION_CAPACITY) X (CRUDE_OIL_VOLUME) = Demand_of_Distributors(DoD)**

##[cap][cov]=[dod]

###We have to find crude oil volume i.e. cov



---



In [ ]:
# Production capacity
cap=np.array([[20,4,4],
              [10,14,5],
              [5,5,12]])

In [ ]:
print(cap)

[[20  4  4]
 [10 14  5]
 [ 5  5 12]]


In [ ]:
cap.shape

(3, 3)

In [ ]:
dod=np.array([6600,5100,3100])
dod.shape

(3,)

In [ ]:
cov=np.linalg.solve(cap,dod)
print(cov)

[287.25 128.75  85.  ]


In [ ]:
print(f'Crude oil volume needed by \n\n Factory A is {round(cov[0])} barrels \n Factory B is {round(cov[1])} barrels \n Factory C is {round(cov[2])} barrels')


Crude oil volume needed by 

 Factory A is 287 barrels 
 Factory B is 129 barrels 
 Factory C is 85 barrels


Suppose the total demand for all products **doubled**. What would the solution now be? How does it compare to the original solution? Why, mathematically, should this have been expected?

###As demand of distributors is doubled, assuming the new demand as **new_dod**, we will calculate it as

In [ ]:
new_dod=2*dod # New demand of ditributors is doubled
print(new_dod)

[13200 10200  6200]


###**(PRODUCTION_CAPACITY) X (NEW_CRUDE_OIL_VOLUME) = New_Demand_of_Distributors(DoD)**

##[cap][new_cov]=[new_dod]

###We have to find new crude oil volume i.e. new_cov ASSUMING that production capacity remains fixed

In [ ]:
new_cov=np.linalg.solve(cap,new_dod)

print(new_cov)
print(f'New crude oil volume needed when we doubled the demand of distributors by \n\n Factory A is {round(new_cov[0])} barrels \n Factory B is {round(new_cov[1])} barrels \n Factory C is {round(new_cov[2])} barrels')


[574.5 257.5 170. ]
New crude oil volume needed when we doubled the demand of distributors by 

 Factory A is 574 barrels 
 Factory B is 258 barrels 
 Factory C is 170 barrels


###As production capacity of plants is fixed, so any change in demand is going to impact the crude oil need which got doubled in this case

Suppose that the company acquires another group of distributors and that the daily demand of this group is 2000 gallons of motor oil, 4000 gallons of gasoline, and 4000 gallons of diesel oil. How would you set up production of just this supply? Are there any options (more than one way)?

###As we got new distributors, their new demand will be represented by **dod_newd** (demand of new distributors)

In [ ]:
dod_newd=np.array([2000, 4000, 4000])

###The combined demand is given by adding previous demand and new distibutors demand.  Combined demand will be denoted by **dod_combined** = **dod + dod_newd**

In [ ]:
dod_combined = dod + dod_newd # Combining the old and new demand of distributors
print(dod_combined)

[8600 9100 7100]


Next, calculate the needs of each factory (in barrels of crude, as usual) to meet the total demand of both groups of distributors. When you have done this, compare your answer to results already obtained. What mathematical conclusion can you draw?

In [ ]:
cov_combined = np.linalg.solve(cap,dod_combined) # Combined crude oil volume need for factories

In [ ]:
print(cov_combined)

[299.75 316.25 335.  ]


In [ ]:
print(f'New combined crude oil volume needed when we combined the demand of old and newly added distributors by \n\n Factory A is {round(cov_combined[0])} barrels \n Factory B is {round(cov_combined[1])} barrels \n Factory C is {round(cov_combined[2])} barrels')


New combined crude oil volume needed when we combined the demand of old and newly added distributors by 

 Factory A is 300 barrels 
 Factory B is 316 barrels 
 Factory C is 335 barrels



###Just for the comparison, the crude oil volume (in barrels) needed to meet the older demand of distributors was
---



In [ ]:
print(f' Factory A is {round(cov[0])} barrels \n Factory B is {round(cov[1])} barrels \n Factory C is {round(cov[2])} barrels')

 Factory A is 287 barrels 
 Factory B is 129 barrels 
 Factory C is 85 barrels





---


---




### Sensitivity and Robustness (1 point)

In real life applications, constants are rarely ever exactly equal to their stated value; certain amounts of uncertainty are always present. This is part of the reason for the science of statistics. In the above model, the daily productions for the plants would be averages over a period of time. Explore what effect small changes in the parameters have on the output.

To do this, pick any 3 coefficients, one at a time, and increase or decrease them by 3%. For each case , note what effect this has on the solution, as a percentage change. Can you draw any overall conclusion?

In [ ]:
print(cap)

[[20  4  4]
 [10 14  5]
 [ 5  5 12]]


In [ ]:
cap[:,0]

array([20, 10,  5])

In [ ]:
#Ask for input
cap_inc = float(input('Enter the raise/decrease % (e.g., for 3% enter 0.03)'))

varying_cap = cap # Creating the varying capacity matrix from Capacity matrix
randomly_selected_feature_index = rnd.randint(0, 2) # Creating a random number b/w 0 and 2 to select the column index
print(f" Randomly selected the colum index is {randomly_selected_feature_index} which is column-{randomly_selected_feature_index+1} in the matrix")

varying_cap = varying_cap.astype(float) # Ensuring the data type is float
varying_cap[:,randomly_selected_feature_index]*= (1+cap_inc) # Experimenting by increasing it by 3%
print(varying_cap)

Enter the raise/decrease % (e.g., for 3% enter 0.03)0.03
 Randomly selected the colum index is 0 which is column-1 in the matrix
[[20.6   4.    4.  ]
 [10.3  14.    5.  ]
 [ 5.15  5.   12.  ]]


In [ ]:
varying_cov=np.linalg.solve(varying_cap,dod)

In [ ]:
print(f'Varying Crude oil volume needed by increasing all the coefficients by 3% taking only one column randomly is \n\n Factory A is {round(varying_cov[0])} barrels \n Factory B is {round(varying_cov[1])} barrels \n Factory C is {round(varying_cov[2])} barrels')

Varying Crude oil volume needed by increasing all the coefficients by 3% taking only one column randomly is 

 Factory A is 279 barrels 
 Factory B is 129 barrels 
 Factory C is 85 barrels


In [ ]:
# Old
print(f' Factory A is {round(cov[0])} barrels \n Factory B is {round(cov[1])} barrels \n Factory C is {round(cov[2])} barrels')

change_perc = ((varying_cov-cov)/cov)*100
print(f" The percentage change for A factory is {round(change_perc[0])} and for B & C are {round(change_perc[1])} & {round(change_perc[2])} respectively")


 Factory A is 287 barrels 
 Factory B is 129 barrels 
 Factory C is 85 barrels
 The percentage change for A factory is -3 and for B & C are 0 & 0 respectively


####ask user to input percentage and increase/decrease and convert randomly selected index to translate to the known x,yz or factory name A, B, C so that it is figured out what changed and for which particular factory.

If we change the individual co-eff one at a time, then the change in output (barrels prodcuced) is negligible.

### A Plant Off-Line (1 point)

Suppose factory $C$ is shut down by the EPA (Environmental Protection Agency) temporarily for excessive emissions into the atmosphere. If your demand is as it was originally (6600, 5100, 3100), what would you now say about the companies ability to meet it? What do you recommend they schedule for production now?

In [ ]:
cap

array([[20,  4,  4],
       [10, 14,  5],
       [ 5,  5, 12]])

###As factory C is shut down, its capacity would be zero and only factories A and B will run at their fixed capacity i.e. **cap**

###Demand of distributors remains the same i.e. **dod**

###We need to slice the capacity matrix to fetch only first two columns making third column belonging to C as zero



---




Using 0 values for Factory C, we got singular matrix error which means that there is no solution. Hence, we used '**Least Square**' method which gave us an approximate solution.

In [ ]:
c_shut_cap=cap
#c_shut_cap[:,2]=[0,0,0]
c_shut_cap=np.delete(c_shut_cap,2,axis=1)
print(c_shut_cap)

[[20  4]
 [10 14]
 [ 5  5]]


In [ ]:
dod.shape # shape of demand matrix

(3,)

In [ ]:
c_shut_cov=np.linalg.lstsq(c_shut_cap,dod,rcond=None)
print(c_shut_cov[0])

[299.47204969 168.47826087]


The solution that we have an overdetermined. Hence, it does not give the unique solution.




---



---



### Buying another plant

####(Note the following given information. You will see questions in continuation to this, in the subsequent sections)

This situation has caused enough concern that the CEO is considering buying another plant, identical to the third, and using it permanently. Assuming that all 4 plants are on line, what production do you recommend to meet the current demand (5000, 8500, 10000)? In general, what can you say about any increased flexibility that the 4th plant might provide?

Let the number of barrels used by factory $A$, $B$, $C$ and $D$ are $x$, $y$, $z$ and $w$ respectively.

Then the system of linear equations will be

$$20x + 4y + 4z + 4w = 5000$$

$$10x + 14y + 5z + 5w = 8500$$

$$5x + 5y + 12z + 12w = 10000$$

The above system of linear equation has fewer equations than variables, hence it is *underdetermined* and cannot have a unique solution. In this case, there are either infinitely many solutions or no exact solution. We can solve it by keeping $w$ as constant and using [rref](http://linear.ups.edu/html/section-RREF.html) form to solve the system of linear equation.

To know about rref implementation in python refer [here](https://docs.sympy.org/latest/tutorial/matrices.html#rref).

In [ ]:
import sympy as sy

# create symbol 'w'
w = sy.Symbol("w")
A_aug = sy.Matrix([[20, 4, 4, 5000-4*w],
                   [10, 14, 5, 8500-5*w],
                   [5, 5, 12, 10000-12*w]])
# show rref form
A_aug.rref()

(Matrix([
 [1, 0, 0,   195/4],
 [0, 1, 0,  1325/4],
 [0, 0, 1, 675 - w]]),
 (0, 1, 2))

From the above result, it can be seen that 4th plant will share the number of barrels required by the 3rd plant only, while the requirement of 1st and 2nd plant will remain unaffected.

### Calculate the amount of Paraffin supplied (1 point)

The company has just found a candle company that will buy its paraffin. Under the current conditions (i.e, after buying another plant) for demand (5000, 8500, 10000), how much can be supplied to them per day?

According to the problem statement, factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude oil, factory $B$ 5 gallons, and factory $C$ 2 gallons.

In [ ]:
import numpy as np
paraffin = np.array([3, 5, 2]) # Paraffin volume in barrel disposed of per barrel of crude oil

new_demand_curcond = np.array([5000, 8500, 10000])
#new_demand_curcond = np.array([2000, 2000, 8000]) # experimenting
#print('new_demand_curcond is',new_demand_curcond)
#print('Dod is     ',dod)

cap[:,2]=[8,10,24] # doubling the capacity of factory C and D since they are sharing the production

print(cap)
print(paraffin)
####
cov_test = np.linalg.solve(cap,new_demand_curcond) # Combined crude oil volume need for factories
print(cov_test)
#####

out_paraf = cov_test*paraffin  # Projection to get the parafin volume as per new demand
print(out_paraf)
out_paraf = (sum(out_paraf).astype(int))

print(f"The total paraffin volume that can be supplied is {out_paraf} gallons per day")

[[20  4  8]
 [10 14 10]
 [ 5  5 24]]
[3 5 2]
[ 48.75 331.25 337.5 ]
[ 146.25 1656.25  675.  ]
The total paraffin volume that can be supplied is 2477 gallons per day


### Selling the first plant (1 point)

The management is also considering selling the first plant due to aging equipment and high workman's compensation costs for the state it is located in. They would like to know what this would do to their production capability. Specifically, they would like an example of a demand they could not meet with only plants 2 and 3, and also what effect having plant 4 has (recall it is identical to plant 3). They would also like an example of a demand that they could meet with just plants 2 and 3. Any general statements you could make here would be helpful.

Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

When considering only plants 2 and 3, and demand (5000, 8500, 10000) then we have

$$4y + 4z = 5000$$

$$14y + 5z = 8500$$

$$5y + 12z = 10000$$

In [ ]:
not_A = np.array([[4, 4], [14, 5],[5, 12]]) # gallons per barrel leaving Factory A out --- (3x2)

demand = np.array([5000, 8500, 10000]) #demand in barrels -- (3x1) matrix
#demand = np.array([6000, 5100, 3100]) # experimental scenario  ------ [348.80820276 193.37298593]

print(not_A.shape)
print(demand.shape)

X = np.linalg.lstsq(not_A, demand)
print(X) # Index 0 = Solution, 1 = Residuals, 2 = rank, 3 = Singular Values

(3, 2)
(3,)
(array([369.30178881, 695.03750721]), array([607616.84939411]), 2, array([18.95513121,  7.91852263]))


<ipython-input-90-82d7035ed5ee>:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  X = np.linalg.lstsq(not_A, demand)


Taking 4th plant into consideration.
Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

Then for demand (5000, 8500, 10000) the system of linear equations will be

$$4y + 4z + 4w = 5000$$

$$14y + 5z + 5w = 8500$$

$$5y + 12z + 12w = 10000$$

Solve it using rref form.

In [ ]:
incl_D = sy.Matrix([[4, 4, 4],
                    [14, 5, 5],
                    [5, 12, 12]]) # Production capacity of the factories - including Factory B, C and D
demand_D = sy.Matrix([5000, 8500, 10000]) #demand in barrels

incl_D.rref()
print(incl_D.rref())

rref_form, pivot_cols = incl_D.rref() # "A simplified version of the original matrix" and "A pivot column is a column that contains a leading 1 in the RREF"
#print(rref_form)

incl_D=np.delete(incl_D,2,axis=1) # Delete 3rd column of the matrix
incl_D[:,1] = incl_D[:,1]*2 # Combining the 2nd and 3rd columns
incl_D = np.array(incl_D) # Ensuring the matrix is a numpy array
demand_D = np.array(demand_D) # Ensuring the matrix is numpy array
#print(incl_D)

incl_D = incl_D.astype(float) # Ensuring the type is float
demand_D = demand_D.astype(float) # Ensuring the type is float
X = np.linalg.lstsq(incl_D, demand_D, rcond= None) # Using Least square method to solve
print(X[0])
tot_barr = sum(X[0]).astype(int) # 0 = X, 1 = residuls, 2 = rank, 3 = ndarray
f_B = 369
f_C = 347
f_D = 347

print(f" Total barrels that are required to meet the demand is {tot_barr+f_D}")
print(f" Total barrels that are required to meet the demand by Factory B is {f_B}")
print(f" Total barrels that are required to meet the demand by Factory C & D is {f_C} each")


(Matrix([
[1, 0, 0],
[0, 1, 1],
[0, 0, 0]]), (0, 1))
[[369.30178881]
 [347.51875361]]
 Total barrels that are required to meet the demand is [1063]
 Total barrels that are required to meet the demand by Factory B is 369
 Total barrels that are required to meet the demand by Factory C & D is 347 each


**CONCLUSION**:

 Since, there is no maximum production capacity given for factories and we can split the demand to other available factories to compensate the absence of Factory A
  
###########################################



Now, changing demand to (6600, 5100, 3100) and solving the system of equation using rref form.

In [ ]:
incl_D1 = sy.Matrix([[4, 4, 4],
                    [14, 5, 5],
                    [5, 12, 12]]) # Production capacity of the factories - including Factory B, C and D
demand_D1 = sy.Matrix([6600, 5100, 3100]) #demand in barrels

incl_D1.rref() #reduced row echelon form of matrix including Factory D
print(incl_D1.rref())

rref_form, pivot_cols = incl_D1.rref() # "A simplified version of the original matrix" and "A pivot column is a column that contains a leading 1 in the RREF"
print(rref_form)

incl_D1=np.delete(incl_D1,2,axis=1) # Delete 3rd column of the matrix
incl_D1[:,1] = incl_D1[:,1]*2 ## Combining the 2nd and 3rd columns
incl_D1 = np.array(incl_D1) # Ensuring the matrix is a numpy array
demand_D1 = np.array(demand_D1) # Ensuring the matrix is a numpy array
print(incl_D1)

incl_D1 = incl_D1.astype(float) # Ensuring the type is float
demand_D1 = demand_D1.astype(float) # Ensuring the type is float
X1 = np.linalg.lstsq(incl_D1, demand_D1, rcond= None)  # Using Least square method to solve,
barr = sum(X1[0])
print(X1[0])
fac_D = 101.53
print(f" Total barrels that are required to meet the demand is {int(barr+fac_D)}")


(Matrix([
[1, 0, 0],
[0, 1, 1],
[0, 0, 0]]), (0, 1))
Matrix([[1, 0, 0], [0, 1, 1], [0, 0, 0]])
[[4 8]
 [14 10]
 [5 24]]
[[352.96284788]
 [101.53357894]]
 Total barrels that are required to meet the demand is 556




---



---



### Set rates for Products (1 point)

Company wants to set the rates of motor oil, diesel oil, and gasoline. For this purpose they have few suggestions given as follows:

* 100, 66, 102 Rupees per gallon,

* 104, 64, 100 Rupees per gallon,

* 102, 68, 98 Rupees per gallon, and

* 96, 68, 100 Rupees per gallon

for motor oil, diesel oil, and gasoline respectively.

Using matrix multiplication, find the rates which result in maximum total price.

Let $M$ denote the matrix such that rows represents different plants (A, B and C), columns represents different products (motor oil, diesel oil and gasoline) and each value represents production of that product from one barrel of crude oil for that plant.

$$M = \begin{bmatrix}
20 & 10 & 5 \\
4 & 14 & 5  \\
 4 & 5 & 12  
\end{bmatrix}$$

Also, $R$ is a matrix having different rates as its columns.

$$R = \begin{bmatrix}
100 & 104 & 102 & 96 \\
66 & 64 & 68 & 68  \\
102 & 100 & 98 & 100  
\end{bmatrix}$$

In [ ]:
R = np.array([[100, 66, 102],
              [104, 64, 100],
              [102, 68, 98],
              [96, 68, 100]]).T # Price matrix in correct format
print(R)
M = np.array([[20,4,4], [10,14,5], [5,5,12]]).T #Capacity
print(M)

out = np.matmul(M, R) # Multiplying the matrices (Product x Rate)
print(out)

sugg_sum = np.sum(out, axis = 0) # summing up the values by coulmns
print(sugg_sum)
price_option = (np.argmax(sugg_sum, axis = 0)+1) # adding 1 to idenitify the normal col index
print(f" The suggested price option is: {round(price_option)} as it is yielding the highest i.e., {max(sugg_sum)} from one barrel of crude oil")

print(" Rates which result in max total price are:",R[:,np.argmax(sugg_sum)])

[[100 104 102  96]
 [ 66  64  68  68]
 [102 100  98 100]]
[[20 10  5]
 [ 4 14  5]
 [ 4  5 12]]
[[3170 3220 3210 3100]
 [1834 1812 1850 1836]
 [1954 1936 1924 1924]]
[6958 6968 6984 6860]
 The suggested price option is: 3 as it is yielding the highest i.e., 6984 from one barrel of crude oil
 Rates which result in max total price are: [102  68  98]


### Marginal Cost (1 point)

The total cost $C(x)$ in Rupees, associated with the production of $x$ gallons of gasoline is given by

$$C(x) = 0.005 x^3 – 0.02 x^2 + 30x + 5000$$

Find the marginal cost when $22$ gallons are produced, where, marginal cost means the instantaneous rate of change of total cost at any level of output.

In [ ]:
import sympy as sp
x = sp.symbols('x')
C = 0.005*x**3 - 0.02*x**2 + 30*x + 5000 # Cost's equation
print(C)

out = sp.diff(C, x) # calculates the derivative of the expression C with respect to the variable x.
print(out)

x_value = 22 # assign the x value
m_cost = out.subs(x, x_value) # calculating the marginal cost by substituting x value with x_value (22)
print(f" The marginal cost is: {round(m_cost,2)} per gallon")

0.005*x**3 - 0.02*x**2 + 30*x + 5000
0.015*x**2 - 0.04*x + 30
 The marginal cost is: 36.38 per gallon


### Marginal Revenue (1 point)

The total revenue in Rupees received from the sale of $x$ gallons of a motor oil is given by $$R(x) = 3x^2 + 36x + 5.$$

Find the marginal revenue, when $x = 28$, where, marginal revenue means the rate of change of total revenue with respect to the number of items sold at an instant.

In [ ]:
R = 3*x**2 + 36*x + 5 # Marginal Revenue equation
print(R)

out1 = sp.diff(R, x) # calculates the derivative of the expression C with respect to the variable x.
print(out1)

x_value = 28 # Assign the value
m_rev = out1.subs(x, x_value)  # calculating the marginal revenue by substituting x value with x_value (28)
print(f" The marginal revenue is: {round(m_rev)} per gallon")

3*x**2 + 36*x + 5
6*x + 36
 The marginal revenue is: 204 per gallon


### Pouring crude oil in tank (1 point)

In a cylindrical tank of radius 10 meter, crude oil is being poured at the rate of 314 cubic meter per hour. Then find

* the rate at which the height of crude oil is increasing in the tank, and
* the height of crude oil in tank after 2 hours.

In [ ]:
import sympy as sp
t = sp.symbols('t')
pi = sp.symbols('pi')
r = sp.symbols('r')
h = sp.symbols('h')

volume = h*pi*r**2
print(volume)

phflow = 314*t # Equation for flow rate for time 't'

r = 10
pi = 3.14
height = phflow/(pi*r**2)
print(height)

height_rate = sp.diff(height, t)
print(format(height_rate,"0.2f"))
print(f"\nThe rate at which the height of the crude oil is increasing in the tank is {height} where t is instantaneuous time. \n")
print(f"The height of the filled crude oil volume after 2 hours in the tank is {height.subs(t,2)} mtrs.")

h*pi*r**2
1.0*t
1.00

The rate at which the height of the crude oil is increasing in the tank is 1.0*t where t is instantaneuous time. 

The height of the filled crude oil volume after 2 hours in the tank is 2.00000000000000 mtrs.
